# Generated by Django 4.2.3 on 2023-07-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akueapi', '0003_alter_detailscommande_detailscompro'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='comTypeValidation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='akueapi.typevalidation'),
        ),
    ]
